rvm:
  - 1.8.7
#  - 1.9.2
  - 1.9.3
  - 2.0.0

script: bundle exec rake spec

gemfile:
  - Gemfile
  - Gemfile.ruby187

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: 1.9.3
      gemfile: Gemfile.ruby187
    - rvm: 2.0.0
      gemfile: Gemfile.ruby187
